# -*- coding: utf-8 -*-
"""Basic_python.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FlEdQbn6hshuLWDzxo6wLRHgEQwiswL3
"""



"""# **Prime Numbers**"""

def prime(n):   # 'prime' is function name
    # Check if the number is less than or equal to 1
    if n <= 1:
        return False

    # Check from 2 to the square root of n
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False

    return True

# Test the function
a = int(input("Enter a number: "))
if prime(a):
    print(f"{a} is a prime number.")
else:
    print(f"{a} is not a prime number.")

"""# Product of Random Number"""

# Product of Random Number

import random  # imports the 'random' modules containing functions for creating random numbers.

def random_numbers():  # This function two random integers between 1 to 10 using "random.randint" function
    num1 = random.randint(1,10)
    num2 = random.randint(1,10)
    return num1, num2

def main():
    num1, num2 = random_numbers()
    print(f"Multiply {num1} and {num2}")

    user_answer = int(input("Enter the your answer: "))
    correct_answer = num1 * num2

    if user_answer == correct_answer:  # Compare the answers
        print("Correct! Well done.")
    else:
        print(f"Incorrect. The correct answer is {correct_answer}.")
if __name__ == "__main__":   # The main function creates two random numbers and asks the user to find their product.
    main()

"""# Square of Even/Odd Numbers"""

# This script prints the squares of all odd numbers within the range of 100 to 200.

def even_squares(start, end):
    for i in range(start, end + 1):
        if i % 2 == 0:
            print(f"The square of {i} is {i ** 2}")

# Define the range
a = 100
b = 200

# Call the function to print the squares of even numbers
even_squares(a, b)

# This script prints the squares of all odd numbers within the range of 100 to 200.

def odd_squares(start, end):
    for number in range(start, end + 1):
        if number % 2 != 0:
            print(f"The square of {number} is {number ** 2}")

# Define the range
a = 100
b = 200

# Call the function to print the squares of even numbers
odd_squares(a, b)

"""# Word counter"""

def count_words(input_text):  # Create function  'count_words' and takes a parameters 'input_text'
    # Split the text into words
    words = input_text.split()

    # Create a dictionary to store the word counts
    word_counts = {}

    # Iterate over each word in the list
    for word in words:
        # If the word is already in the dictionary, increment its count
        if word in word_counts:
            word_counts[word] += 1
        # Otherwise, add the word to the dictionary with a count of 1
        else:
            word_counts[word] = 1

    return word_counts

# Example usage
input_text = "This is a sample text. This text will be used to demonstrate the word counter."
word_counts = count_words(input_text)

# Print the word counts
for word, count in word_counts.items():
    print(f"'{word}': {count}")

"""# Check for Palindrome"""

import re

def is_palindrome(input_string):
    # Remove non-alphanumeric characters and convert to lowercase
    cleaned_string = re.sub(r'[^A-Za-z0-9]', '', input_string).lower()

    # Check if the cleaned string is equal to its reverse
    return cleaned_string == cleaned_string[::-1]

# Example usage
input_string = "racecar"
print(is_palindrome(input_string))  # Expected output: True

input_string = "A man, a plan, a canal, Panama"
print(is_palindrome(input_string))  # Expected output: True

input_string = "hello"
print(is_palindrome(input_string))  # Expected output: False

