# -*- coding: utf-8 -*-
"""Basic Statict.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FlEdQbn6hshuLWDzxo6wLRHgEQwiswL3
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv("sales_data_with_discounts.csv")
df

df.info()

# Identify numerical columns
numerical_cols = df.select_dtypes(include=[np.number]).columns

# Calculate statistical measures
statistics = df[numerical_cols].describe().transpose()
mode = df[numerical_cols].mode().transpose()
statistics['mode'] = mode[0]

# Print statistics
print(statistics)

#Data Visualization

# Histograms
for col in numerical_cols:
    plt.figure()
    sns.histplot(df[col], kde=True)
    plt.title(f'Histogram of {col}')
    plt.show()

# Boxplots
for col in numerical_cols:
    plt.figure()
    sns.boxplot(x=df[col])
    plt.title(f'Boxplot of {col}')
    plt.show()

# Bar Chart Analysis for Categorical Columns
categorical_cols = df.select_dtypes(include=['object']).columns
for col in categorical_cols:
    plt.figure()
    df[col].value_counts().plot(kind='bar')
    plt.title(f'Bar Chart of {col}')
    plt.show()

# Standardization

standardized_df = (df[numerical_cols] - df[numerical_cols].mean()) / df[numerical_cols].std()
#print(standardized_df)
print(standardized_df.describe().transpose())

# Conversion of Categorical Data into Dummy Variables

Dummy= pd.get_dummies(df, columns=categorical_cols)
print(Dummy.head())

# Summarize findings
print("Descriptive analytics, data visualizations, and preprocessing steps completed.")

