# -*- coding: utf-8 -*-
"""Chi-square.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FlEdQbn6hshuLWDzxo6wLRHgEQwiswL3

# Importing Library and Data
"""

import numpy as np
import scipy.stats as stats

# Data provided
data = np.array([
    [50,70],  # Very Satisfied
    [80,100],  # Satisfied
    [60,90],  # Neutral
    [30,50],  # Unsatisfied
    [20,50]   # Very Unsatisfied
])

# Find the chi-square statistic

chi_stat, p_value, dof, ex = stats.chi2_contingency(data)
print("Chi-square statistic: ", chi_stat)
print("P_value test: ", p_value)
print("Degree of freedom:", dof)
print("Expected Frequencies:", ex)

# Determine the Critical Value
alpha = 0.05
cr_value = stats.chi2.ppf(1 - alpha, dof)
print("Critical Value:",cr_value)

# Compare the chi-square statistic to the critical value and make a decision
if chi_stat > cr_value:
    print("Rejected null hypothesis, accepted alternative hypothesis")
else:
    print("Accepted null hypothesis, rejected alternative hypothesis")