# -*- coding: utf-8 -*-
"""Hypothesis-testing.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FlEdQbn6hshuLWDzxo6wLRHgEQwiswL3

# Importing Library and Data
"""

import math
from scipy.stats import norm

# Given Data
X = 3050    # Sample mean weekly cost
theoretical_cost = 1000   # Fixed cost in the model
cost_per_unit = 5         # Cost per unit
X = 600                  #Number of units produced in a week
S = 125    # Standard deviation (5 * 25)
n = 25   # Size

U = theoretical_cost + cost_per_unit * X
U

# Calculate the test statistic
t_stat = (X - U) / (S/math.sqrt(n))
t_stat

# Determine the critical value at alpha = 0.05 for a one-tailed test
alpha = 0.05
cr_value = norm.ppf(1 - alpha)   # Z critical value for one-tailed test
cr_value

# Decision
if t_stat > cr_value:
    print("Reject the null hypothesis, accept the alternative hypothesis")
else:
    print("Accept the null hypothesis, rejected the alternative hypothesis")

# Conclusion
if t_stat > cr_value:
    print("The restaurant owners have strong evidence that weekly operating costs exceed the model's estimate:")
else:
    print("There is insufficient evidence to support the restaurant owners' claim:")

